#!/usr/bin/perl

use strict;

description("Reset HAPS");
autodie();

sub main {
    if (haps_check_requirement()) {
        exit 1;
    }

    my $emu = haps_get_device();
    if (!defined $emu) {
        print "No device found\n";
        exit 0;
    }

    cmd("confpro $emu cfg_reset_pulse FB1");
}

main();
