#!/usr/bin/perl

use strict;
use File::Which;

description("Reset HAPS");
autodie();

sub main {
    if (system("which confpro > /dev/null")) {
        print "confpro not found\n";
        exit 1;
    }

    if (! grep { /umrusb/ } `lsmod` ) {
        print "umrusb driver is not loaded\n";
        exit 1;
    }

    my $output;
    cmd("confpro cfg_scan", \$output);
    if (!defined $output) {
        print "No device found\n";
        exit 0;
    }

    my @devices = ($output =~ m/emu:\d+?/g);
    my @serials = ($output =~ m/SERIAL \{.+?\}/g);
    my $emu;

    if (@devices == 1) {
        $emu = $devices[0];
    } elsif (@devices > 1) {
        my $num;

        SELECT:
        print "Select device number below:\n";
        my $count = 1;
        for (@devices) {
            print "$count) $serials[$count++ - 1]\n";
        }

        print "Device: ";
        $num = <STDIN>;
        chomp $num;
        if (($num !~ m/\d+/) || ($num >= $count) || ($num <= 0)) {
            print "Please provide a valid number\n\n";
            goto SELECT;
        }

        $emu = $devices[$num - 1];
    } else {
        print "Couldn't find device number\n";
        exit 1;
    }

    cmd("confpro $emu cfg_reset_pulse FB1");
}

main();
