#!/usr/bin/perl

use strict;

description("Load the dwc3 xhci driver");
no_options();
run_as_root();

cmd("$SCRIPT_DIR/unload");

if (plat_is_arc() or plat_is_juno()) {
    system("modprobe -q phy-generic");
    cmd("modprobe xhci_plat_hcd");
    cmd("modprobe dwc3");
} elsif (plat_is_x86()) {
    cmd("modprobe xhci_pci");
    cmd("modprobe xhci_hcd");
}

cmd("$SCRIPT_DIR/enable_trace");
