#!/usr/bin/perl

use strict;

description("Load the dwc3 xhci driver");
run_as_root();

sub main {
    my $arg = shift @ARGV;

    unload();

    if (plat_is_arc() or plat_is_juno()) {
        system("modprobe -q phy-generic");
        cmd("modprobe xhci_plat_hcd");
        cmd("modprobe dwc3");
    } elsif (plat_is_x86()) {
        if (base()) {
            cmd("modprobe dwc3");
            if (system("modprobe -q dwc3_haps")) {
                cmd("modprobe dwc3_pci");
            }
        } else {
            cmd("modprobe xhci_pci");
        }

        cmd("modprobe xhci_hcd");
    }

    if (defined $arg) {
        if ($arg eq 'typec') {
            cmd("modprobe snps-phy-tc");
        }
    }

    enable_trace();
}

main();
