#!/usr/bin/perl

use strict;
use Cwd qw(abs_path);
use File::Basename qw(dirname);

my $DIR = dirname(abs_path($0));
$DIR = "$DIR/..";

if (!-d "$DIR/.git") {
    # Versioning not support outside of git
    if (!-f "$DIR/.gitversion") {
	print "Not in git repository\n";
    }

    system("cp $DIR/.gitversion $DIR/VERSION");
    print "Couldn't create VERSION\n" if $?;

    exit(0);
}

my $out = `git rev-parse --short HEAD`;

chomp $out;
system("echo $out > $DIR/VERSION");
