#!/usr/bin/perl

use strict;

dwc_script();

description("Print controller id");
run_as_root();
no_options();

sub main {
    my $id;

    if ($TYPE eq "dwc2") {
        $id = rreg(0x40);
    } else {
	$id = rreg(0xc120);
    }

    printf("%x\n", $id);
}

main();
