#!/usr/bin/perl

use strict;

description("Read register");
run_as_root();

sub usage {
    my $exit_code = shift;

    print <<EOF;
usage: $SCRIPT <offset> [<bits>]

Read the register value at <offset>.

<offset> is in hex.
<bits> is an integer or bitfield.

Example:
    rreg c120 15:0
EOF

    exit $exit_code;
}

sub main {
    my $offset = $ARGV[0];
    my $bitfield = $ARGV[1];

    usage(0) unless defined $offset;

    if (!validate_hex($offset)) {
        die("Invalid hex offset $offset\n");
    }

    $offset = hex($offset);

    my $no_base;
    if ($SCRIPT eq "rd") {
        $no_base = 1;
    }

    my $value = rreg($offset, $no_base);

    usage(1) unless defined $value;

    my $hex_string = sprintf "%08x\n", $value;

    if (defined $bitfield) {
        printf "\nRegister: %x\n", $offset;
        system("$BIN_DIR/dx", $hex_string, $bitfield);
    } else {
        printf "$hex_string";
    }

    exit(0);
}

main();
