#!/usr/bin/perl

use strict;

description("Print information about the controller");
run_as_root();
no_options();

# Check if PCIe device is in PCI bus
base();

# Check if device ID is correct
my $snpsid = rreg(0xc120) >> 16;
if (($snpsid != 0x5533) && ($snpsid != 0x3331)) {
    die sprintf("Error: Wrong device ID %04x\n", $snpsid);
}

# Check if driver is loaded
print "\n";
my $tmp;

cmd("lsmod", \$tmp) or die;
if ($tmp =~ /dwc3/ and $tmp =~ /g_mass_storage/) {
    print "Driver is loaded\n";
} else {
    print "Driver is NOT loaded\n";
}

my $GDBGLTSSM = rreg(0xc164);
my $num = $GDBGLTSSM;
$num = $num & 0x03C00000;
$num = ($num >> 22) ;

my $state;
if ($num == 0) { $state = "U0"; }
elsif ($num == 1) { $state = "U1"; }
elsif ($num == 2) { $state = "U2"; }
elsif ($num == 3) { $state = "U3"; }
elsif ($num == 4) { $state = "SS_disable"; }
elsif ($num == 5) { $state = "Rx_Detect "; }
elsif ($num == 6) { $state = "SS_Inactive"; }
elsif ($num == 7) { $state = "Poll"; }
elsif ($num == 8) { $state = "Recov"; }
elsif ($num == 9) { $state = "HReset"; }
elsif ($num == 10) { $state = "Compliance"; }
elsif ($num == 11) { $state = "Loopback"; }
else { $state = "Unknown"; }
printf "LinkState = $state (0x%02x)\n", $num;

$num = $GDBGLTSSM & 0x3C0000;
$num = $num >> 18;
printf("Sub LinkState = %x\n", $num);

# Find device speed
my $DSTS = rreg(0xc70c);
$num = $DSTS & 7;

my $speed;
if ($num == 4) { $speed = "Super speed gen1"; }
elsif ($num == 5) { $speed = "Super speed gen2"; }
elsif ($num == 0) { $speed = "High speed"; }
elsif ($num == 1) { $speed = "Full speed"; }
elsif ($num == 2) { $speed = "Low speed"; }
elsif ($num == 3) { $speed = "Full speed"; }
else { $speed = "Unknown"; }
print "Speed: $speed\n";

#Find MPHY state
my $GUSB3RMMICTL = rreg(0xc1c0);
print "GUSB3RMMICTL = $GUSB3RMMICTL\n";
$num = ($GUSB3RMMICTL & 0x0E000000) >> 25;

my $mphy_state;

if ($num == 0) { $mphy_state = "disable"; }
elsif ($num == 1) { $mphy_state = "hibern8"; }
elsif ($num == 2) { $mphy_state = "sleep  "; }
elsif ($num == 3) { $mphy_state = "STALL"; }
elsif ($num == 4) { $mphy_state = "PWM_burst"; }
elsif ($num == 5) { $mphy_state = "HS-BURST"; }
elsif ($num == 6) { $mphy_state = "line_cfg"; }
elsif ($num == 7) { $mphy_state = "line_reset"; }
else { $mphy_state = "Unknown"; }
printf "MPHY State = $mphy_state (0x%02x)\n", $num;
print "\n";
