#!/usr/bin/perl

use strict;

description("Print information about the controller");
run_as_root();

sub usage {
    my $exit_code = shift;

    print <<USAGE_EOF;
usage: $SCRIPT [eps] | [ep_name [trb_ring]]

Show current controller status and its
endpoints debug info.

Options:
  <NONE>     - print current controller status
  eps        - list all controller's endpoint info
  ep_name    - endpoint name e.g. ep1in, ep2out
  trb_ring   - print endpoint TRB ring of an endpoint

USAGE_EOF

    exit $exit_code;
}

sub print_status {
    my $snpsid = rreg(0xc120);
    my $is_usb31 = ($snpsid >> 16 == 0x3331) ? 1 : 0;
    my $is_usb3 = ($snpsid >> 16 == 0x5533) ? 1 : 0;

    my $GDBGLTSSM;
    my $rtl_ver = "Unknown";

    if ($is_usb31) {
        $GDBGLTSSM = rreg(0xd050);

        my $ver_num = rreg(0xc1a0);
        my $ver_num_ascii = pack "N*", $ver_num;
        $ver_num_ascii =~ s/(\d)(.*?)\*?$/$1.$2a/;

        my $ver_type = rreg(0xc1a4);
        my $ver_type_ascii = pack "N*", $ver_type;
        $rtl_ver = "dwc_usb31 v$ver_num_ascii-$ver_type_ascii";
    } elsif ($is_usb3) {
        $GDBGLTSSM = rreg(0xc164);

        my $ver_num = $snpsid & 0xffff;
        my $ver_num_ascii = sprintf "%x", $ver_num;
        $ver_num_ascii =~ s/(\d)(.*)/$1.$2/;
        $rtl_ver = "dwc_usb3 v$ver_num_ascii";
    }

    my $GHWPARAMS0 = rreg(0xc140);
    my $GCTL = rreg(0xc110);
    my $hw_mode = ($GHWPARAMS0 & 0x3);

    my $hw_mode_name;
    if ($hw_mode == 0) { $hw_mode_name = "device" }
    elsif ($hw_mode == 1) { $hw_mode_name = "host" }
    elsif ($hw_mode == 2) { $hw_mode_name = "drd" }

    my $prtcapdir = ($GCTL >> 12) & 3;

    my $state_num;
    my $state = "Unknown";

    my $speed_num = 4; # default to SuperSpeed
    my $speed = "Unknown";

    if ($hw_mode == 0 || ($hw_mode == 2 && $prtcapdir == 2)) {
        # Find device speed
        my $DSTS = rreg(0xc70c);
        my $lane = ($DSTS & (1 << 30)) ? "2-lane" : "1-lane";

        $state_num = ($DSTS >> 18) & 0xf;
        $speed_num = $DSTS & 7;

        if ($speed_num == 4) { $speed = "Super speed gen1 $lane"; }
        elsif ($speed_num == 5) { $speed = "Super speed gen2 $lane"; }
        elsif ($speed_num == 0) { $speed = "High speed"; }
        elsif ($speed_num == 1) { $speed = "Full speed"; }
        elsif ($speed_num == 2) { $speed = "Low speed"; }
        elsif ($speed_num == 3) { $speed = "Full speed"; }
    } else {
        $state_num = ($GDBGLTSSM >> 22) & 0xf;
    }

    my $sublink_state = "n/a";
    my $link_state = sprintf "0x%02x", $state_num;

    if ($speed_num > 3) {
        $sublink_state = sprintf "0x%02x", ($GDBGLTSSM >> 18) & 0xf;

        if ($state_num == 0) { $state = "U0"; }
        elsif ($state_num == 1) { $state = "U1"; }
        elsif ($state_num == 2) { $state = "U2"; }
        elsif ($state_num == 3) { $state = "U3"; }
        elsif ($state_num == 4) { $state = "SS_disable"; }
        elsif ($state_num == 5) { $state = "Rx_Detect "; }
        elsif ($state_num == 6) { $state = "SS_Inactive"; }
        elsif ($state_num == 7) { $state = "Poll"; }
        elsif ($state_num == 8) { $state = "Recov"; }
        elsif ($state_num == 9) { $state = "HReset"; }
        elsif ($state_num == 10) { $state = "Compliance"; }
        elsif ($state_num == 11) { $state = "Loopback"; }
    } else {
        if ($state_num == 0) { $state = "On"; }
        elsif ($state_num == 2) { $state = "Sleep L1"; }
        elsif ($state_num == 3) { $state = "Suspend L2"; }
        elsif ($state_num == 4) { $state = "Disconnected"; }
        elsif ($state_num == 5) { $state = "Early Suspend"; }
        elsif ($state_num == 14) { $state = "Reset"; }
        elsif ($state_num == 15) { $state = "Resume"; }
    }

    #Find MPHY state
    my $GUSB3RMMICTL = rreg(0xc1c0);
    my $mphy_state_num = ($GUSB3RMMICTL >> 25) & 0x7;

    my $mphy_state;

    if ($mphy_state_num == 0) { $mphy_state = "disable"; }
    elsif ($mphy_state_num == 1) { $mphy_state = "hibern8"; }
    elsif ($mphy_state_num == 2) { $mphy_state = "sleep  "; }
    elsif ($mphy_state_num == 3) { $mphy_state = "STALL"; }
    elsif ($mphy_state_num == 4) { $mphy_state = "PWM_burst"; }
    elsif ($mphy_state_num == 5) { $mphy_state = "HS-BURST"; }
    elsif ($mphy_state_num == 6) { $mphy_state = "line_cfg"; }
    elsif ($mphy_state_num == 7) { $mphy_state = "line_reset"; }
    else { $mphy_state = "Unknown"; }

    print <<"DWC_INFO"
    RTL Version:   $rtl_ver
    HW Mode:       $hw_mode_name
    LinkState:     $state ($link_state)
    Sub LinkState: $sublink_state
    Speed:         $speed
    GUSB3RMMICTL:  $GUSB3RMMICTL
    MPHY State:    $mphy_state ($mphy_state_num)

DWC_INFO
}

sub print_ep {
    my $debugfs = shift;
    my $ep = shift;

    my $desc_fetch_q;
    my $event_q;
    my $rx_info_q;
    my $tx_info_q;
    my $rx_fifo_q;
    my $tx_fifo_q;

    cmd("cat $debugfs/$ep/descriptor_fetch_queue", \$desc_fetch_q);
    cmd("cat $debugfs/$ep/event_queue", \$event_q);
    cmd("cat $debugfs/$ep/rx_fifo_queue", \$rx_fifo_q);
    cmd("cat $debugfs/$ep/tx_fifo_queue", \$tx_fifo_q);
    cmd("cat $debugfs/$ep/rx_info_queue", \$rx_info_q);
    #cmd("cat $debugfs/$ep/tx_info_queue", \$tx_info_q);

    chomp $event_q;
    chomp $event_q;
    chomp $rx_fifo_q;
    chomp $tx_fifo_q;
    chomp $rx_info_q;
    chomp $tx_info_q;

    print <<EP_INFO;
## $ep
desc_fetch_queue = $event_q
event_queue      = $event_q
rx_fifo_queue    = $rx_fifo_q
tx_fifo_queue    = $tx_fifo_q
rx_info_queue    = $rx_info_q
=============================
EP_INFO
}

sub main {
    # Check if PCIe device is in PCI bus
    base();

    if (!@ARGV) {
        print "\n";

        print_status();
        exit(0);
    } else {
        my $debugfs;

        if ($TYPE eq "dwc3") {
            $debugfs = dwc3_debugfs() or die("No debugfs for $TYPE");
        } else {
            die("Endpoint debug is unsupported for $TYPE");
        }

        if ($ARGV[0] eq "eps") {
            my @eps;
            my @files = <"$debugfs/*">;

            foreach my $file (@files) {
                my $name;

                if ($file =~ /(ep\d{1,2}(?:in|out))/) {
                    push @eps, $1;
                }
            }

            foreach my $ep (@eps) {
                print_ep($debugfs, $ep);
            }
        } elsif ($ARGV[0] =~ /(ep\d{1,2}(?:in|out))/) {
            my $ep = shift @ARGV;

            if ($ARGV[0] eq 'trb_ring') {
                cmd("cat $debugfs/$ep/trb_ring");
            } else {
                print_ep($debugfs, $ep);
            }
        } else {
            usage(0);
        }
    }

    exit(0);
}

main();
