#!/usr/bin/perl

use strict;

description("Load the dwc3 module");
no_options();
run_as_root();
autodie();

unload();
initram();

if (plat_is_x86()) {
    cmd("modprobe dwc3_pci");
}

system("modprobe -q phy-generic");
cmd("modprobe dwc3");
enable_trace();
cmd("modprobe g_mass_storage file=/dev/ram0 iSerialNumber=000020160529 removable=0");
