#!/usr/bin/perl

use strict;

description("Unload the dwc3 module");
no_options();
run_as_root();

rmmod("g_mass_storage", "g_audio", "g_zero", "tcm_usb_gadget", "g_uas");
rmmod("usb_f_mass_storage", "usb_f_uac1", "usb_f_uas");
rmmod("usb_f_tcm", "iscsi_target_mod", "tcm_loop", "target_core_mod");
rmmod("dwc3_pci", "dwc3");
rmmod("dwc2_pci", "dwc2");
rmmod("phy_generic");
rmmod("usb_f_mass_storage", "libcomposite", "udc_core");
