#!/usr/bin/perl

use strict;

description("Request remote wakeup");
run_as_root();

sub main {
    my $srp = "/sys/class/udc/dwc3.0.auto/srp";
    if (plat_is_x86() and -e $srp) {
        cmd("echo 1 > $srp");
    }
}

main();
