#!/usr/bin/perl

use strict;

description("Request remote wakeup");
run_as_root();

sub main {
    if (plat_is_x86()) {
        my $debugfs = dwc3_debugfs();
        if (defined $debugfs and -e "$debugfs/wakeup") {
            cmd("echo > $debugfs/wakeup");
        } else {
            die("Remote wakeup is not available\n");
        }
    }
}

main();
