#!/usr/bin/perl

use strict;

description("Load the dwc2 module");
no_options();
run_as_root();
autodie();

unload();
initram();

if (plat_is_x86()) {
    cmd("modprobe dwc2_pci");
}

cmd("modprobe dwc2");
cmd("modprobe g_mass_storage file=/dev/ram0 iSerialNumber=012345678901");
